Library Setup and Loading Data

In [73]:
import pandas as pd
import numpy as np
data = pd.read_csv('comprehensive_mutual_funds_data.csv')
data.head(10)

,scheme_name,min_sip,min_lumpsum,expense_ratio,fund_size_cr,fund_age_yr,fund_manager,sortino,alpha,sd,beta,sharpe,risk_level,amc_name,rating,category,sub_category,returns_1yr,returns_3yr,returns_5yr
0,Aditya Birla SL Active Debt Multi-Mgr FoF-Dir ...,100,100,0.27,10.0,10,Kaustubh Gupta,0.32,2.24,9.39,0.01,0.24,3,Aditya Birla Sun Life Mutual Fund,3,Other,FoFs Domestic,4.0,6.5,6.9
1,Aditya Birla SL Arbitrage Fund,1000,1000,0.36,4288.0,10,Lovelish Solanki,1.33,1.53,0.72,0.56,1.1,1,Aditya Birla Sun Life Mutual Fund,3,Hybrid,Arbitrage Mutual Funds,5.6,4.8,5.5
2,Aditya Birla SL Asset Allocator FoF-Dir Growth,1000,1000,0.53,157.0,10,Vinod Narayan Bhat,3.44,2.67,10.58,0.67,1.42,5,Aditya Birla Sun Life Mutual Fund,3,Other,FoFs Domestic,2.0,18.9,9.7
3,Aditya Birla SL Bal Bhavishya Yojna – Dir Growth,500,1000,0.76,637.0,4,Atul Penkar,2.18,-6.37,14.99,0.85,0.9,6,Aditya Birla Sun Life Mutual Fund,2,Solution Oriented,Childrens Funds,-0.7,17.1,NaN
4,Aditya Birla SL Balanced Advantage Fund,100,100,0.61,6386.0,10,Mohit Sharma,3.69,1.99,10.38,0.68,1.39,6,Aditya Birla Sun Life Mutual Fund,4,Hybrid,Dynamic Asset Allocation or Balanced Advantage,4.5,18.6,9.7
5,Aditya Birla SL Banking&Financial Services-Dir...,1000,1000,1.17,2384.0,9,Dhaval Gala,2.07,1.24,25.53,0.96,0.97,6,Aditya Birla Sun Life Mutual Fund,2,Equity,Sectoral / Thematic Mutual Funds,5.3,24.6,9.2
6,Aditya Birla SL Banking&PSU Debt Fund,1000,1000,0.37,7994.0,10,Kaustubh Gupta,1.92,4.46,1.91,1.78,1.09,3,Aditya Birla Sun Life Mutual Fund,4,Debt,Banking and PSU Mutual Funds,4.5,6.8,7.3
7,Aditya Birla SL CEF – Global Agri Plan-Direct ...,1000,1000,1.29,15.0,10,Vinod Narayan Bhat,1.42,-,20.18,-,1.06,6,Aditya Birla Sun Life Mutual Fund,0,Equity,Sectoral / Thematic Mutual Funds,-10.3,29.4,9.3
8,Aditya Birla SL Corporate Bond Fund,100,100,0.31,12120.0,10,Kaustubh Gupta,2.28,2.38,1.93,0.78,1.35,2,Aditya Birla Sun Life Mutual Fund,4,Debt,Corporate Bond Mutual Funds,4.9,7.1,7.4
9,Aditya Birla SL Credit Risk Fund,100,100,0.69,1032.0,8,Sunaina da Cunha,1.82,3.01,2.9,-0.95,1.47,4,Aditya Birla Sun Life Mutual Fund,4,Debt,Credit Risk Funds,8.7,9.0,7.2

Starting Data Exploration

In [74]:
data['scheme_name'].value_counts()

scheme_name
SBI Long Term Advantage Fund              6
ICICI Pru Retirement Fund                 4
Sundaram LT MC Tax Advantage Fund         3
AXIS Retirement Savings Fund              3
Tata Retirement Savings Fund              3
                                         ..
HSBC Flexi Debt Fund                      1
HSBC Gilt Fund                            1
HSBC Infrastructure Fund                  1
HSBC Large & Mid Cap Fund                 1
WhiteOak Capital Ultra Short Term Fund    1
Name: count, Length: 789, dtype: int64

In [75]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   scheme_name    814 non-null    object
 1   min_sip        814 non-null    int64
 2   min_lumpsum    814 non-null    int64
 3   expense_ratio  814 non-null    float64
 4   fund_size_cr   814 non-null    float64
 5   fund_age_yr    814 non-null    int64
 6   fund_manager   814 non-null    object
 7   sortino        814 non-null    object
 8   alpha          814 non-null    object
 9   sd             814 non-null    object
 10  beta           814 non-null    object
 11  sharpe         814 non-null    object
 12  risk_level     814 non-null    int64
 13  amc_name       814 non-null    object
 14  rating         814 non-null    int64
 15  category       814 non-null    object
 16  sub_category   814 non-null    object
 17  returns_1yr    814 non-null    float64
 18  returns_3yr    793 non-null    float64
 19  returns_5yr    647 non-null    float64
dtypes: float64(5), int64(5), object(10)
memory usage: 127.3+ KB

In [76]:
print(data.fund_age_yr.where(data.returns_5yr.isnull()==True).dropna().sort_values(ascending=False))

644    5.0
114    5.0
700    5.0
124    5.0
695    5.0
      ...
755    2.0
689    2.0
499    2.0
720    2.0
495    2.0
Name: fund_age_yr, Length: 167, dtype: float64

Dealing With Missing Data

In [77]:
# 3 year returns
data['returns_3yr'] = data.apply(lambda row: 0 if pd.isnull(row['returns_3yr']) and row['fund_age_yr'] <= 2 else row['returns_3yr'],axis=1)
m= data.returns_3yr.mean()
data['returns_3yr'] = data.apply(lambda row: m if pd.isnull(row['returns_3yr']) and row['fund_age_yr'] == 3 else row['returns_3yr'],axis=1)

# 5 Year retuns
data['returns_5yr'] = data.apply(lambda row: 0 if pd.isnull(row['returns_5yr']) and row['fund_age_yr'] <= 4 else row['returns_5yr'],axis=1)
n= data.returns_5yr.mean()
data['returns_5yr'] = data.apply(lambda row: n if pd.isnull(row['returns_5yr']) and row['fund_age_yr'] == 5 else row['returns_5yr'],axis=1)

In [78]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   scheme_name    814 non-null    object
 1   min_sip        814 non-null    int64
 2   min_lumpsum    814 non-null    int64
 3   expense_ratio  814 non-null    float64
 4   fund_size_cr   814 non-null    float64
 5   fund_age_yr    814 non-null    int64
 6   fund_manager   814 non-null    object
 7   sortino        814 non-null    object
 8   alpha          814 non-null    object
 9   sd             814 non-null    object
 10  beta           814 non-null    object
 11  sharpe         814 non-null    object
 12  risk_level     814 non-null    int64
 13  amc_name       814 non-null    object
 14  rating         814 non-null    int64
 15  category       814 non-null    object
 16  sub_category   814 non-null    object
 17  returns_1yr    814 non-null    float64
 18  returns_3yr    814 non-null    float64
 19  returns_5yr    814 non-null    float64
dtypes: float64(5), int64(5), object(10)
memory usage: 127.3+ KB

More Exploration

In [79]:
data['category'].value_counts()

category
Equity               308
Debt                 282
Hybrid               116
Other                 80
Solution Oriented     28
Name: count, dtype: int64

In [80]:
data['sub_category'].value_counts()

sub_category
Sectoral / Thematic Mutual Funds                  82
ELSS Mutual Funds                                 52
FoFs Domestic                                     35
Liquid Mutual Funds                               34
Index Funds                                       30
Aggressive Hybrid Mutual Funds                    30
Large Cap Mutual Funds                            28
Overnight Mutual Funds                            26
Small Cap Mutual Funds                            25
Ultra Short Duration Funds                        25
Large & Mid Cap Funds                             24
Mid Cap Mutual Funds                              23
Short Duration Funds                              23
Arbitrage Mutual Funds                            22
Flexi Cap Funds                                   22
Dynamic Bond                                      22
Banking and PSU Mutual Funds                      21
Equity Savings Mutual Funds                       21
Low Duration Funds                                20
Focused Funds                                     20
Retirement Funds                                  20
Gilt Mutual Funds                                 19
Money Market Funds                                19
Corporate Bond Mutual Funds                       19
Dynamic Asset Allocation or Balanced Advantage    19
Conservative Hybrid Mutual Funds                  17
FoFs Overseas                                     15
Medium Duration Funds                             14
Credit Risk Funds                                 14
Value Funds                                       13
Medium to Long Duration Funds                     11
Floater Mutual Funds                              11
Multi Cap Funds                                   10
Childrens Funds                                    8
Multi Asset Allocation Mutual Funds                7
Dividend Yield Funds                               6
Fixed Maturity Plans                               4
Contra Funds                                       3
Name: count, dtype: int64

In [81]:
print(data['sub_category'].where(data['scheme_name'].str.contains("Saving")).dropna())

15          Equity Savings Mutual Funds
40     Conservative Hybrid Mutual Funds
45           Ultra Short Duration Funds
75                     Retirement Funds
76                     Retirement Funds
77                     Retirement Funds
111         Equity Savings Mutual Funds
140                  Low Duration Funds
152         Equity Savings Mutual Funds
168    Conservative Hybrid Mutual Funds
169                  Money Market Funds
183         Equity Savings Mutual Funds
206         Equity Savings Mutual Funds
218                  Money Market Funds
231         Equity Savings Mutual Funds
252                    Retirement Funds
253                    Retirement Funds
254                    Retirement Funds
273         Equity Savings Mutual Funds
311         Equity Savings Mutual Funds
337                       FoFs Domestic
338    Conservative Hybrid Mutual Funds
344                  Low Duration Funds
356         Equity Savings Mutual Funds
380                   ELSS Mutual Funds
390         Equity Savings Mutual Funds
442         Equity Savings Mutual Funds
458          Ultra Short Duration Funds
479                  Low Duration Funds
487         Equity Savings Mutual Funds
502         Equity Savings Mutual Funds
511                  Low Duration Funds
537    Conservative Hybrid Mutual Funds
548         Equity Savings Mutual Funds
551                       FoFs Domestic
586         Equity Savings Mutual Funds
612                       FoFs Domestic
616                   ELSS Mutual Funds
629         Equity Savings Mutual Funds
660                  Money Market Funds
683         Equity Savings Mutual Funds
709                   ELSS Mutual Funds
717         Equity Savings Mutual Funds
726                   ELSS Mutual Funds
736                    Retirement Funds
737                    Retirement Funds
738                    Retirement Funds
762         Equity Savings Mutual Funds
784         Equity Savings Mutual Funds
803    Conservative Hybrid Mutual Funds
Name: sub_category, dtype: object

In [82]:
data.duplicated().sum()

0

Created a primary key column for sql

In [83]:
data['ID']=data['scheme_name']+' '+ data['returns_1yr'].apply(lambda x:str(x))
data.ID.value_counts()

ID
Aditya Birla SL Active Debt Multi-Mgr FoF-Dir Growth 4.0    1
Nippon India Dynamic Bond Fund 3.6                          1
Navi Large Cap Equity Fund 0.2                              1
Navi Regular Savings Fund 4.4                               1
Navi Ultra Short Term Fund 1.7                              1
                                                           ..
HSBC Flexi Cap Fund -1.2                                    1
HSBC Flexi Debt Fund 1.7                                    1
HSBC Gilt Fund 5.0                                          1
HSBC Infrastructure Fund 11.3                               1
WhiteOak Capital Ultra Short Term Fund 5.3                  1
Name: count, Length: 814, dtype: int64

In [84]:
first_column = data.pop('ID')
data.insert(0,'ID',first_column)
data.head(10)

,ID,scheme_name,min_sip,min_lumpsum,expense_ratio,fund_size_cr,fund_age_yr,fund_manager,sortino,alpha,...,beta,sharpe,risk_level,amc_name,rating,category,sub_category,returns_1yr,returns_3yr,returns_5yr
0,Aditya Birla SL Active Debt Multi-Mgr FoF-Dir ...,Aditya Birla SL Active Debt Multi-Mgr FoF-Dir ...,100,100,0.27,10.0,10,Kaustubh Gupta,0.32,2.24,...,0.01,0.24,3,Aditya Birla Sun Life Mutual Fund,3,Other,FoFs Domestic,4.0,6.5,6.9
1,Aditya Birla SL Arbitrage Fund 5.6,Aditya Birla SL Arbitrage Fund,1000,1000,0.36,4288.0,10,Lovelish Solanki,1.33,1.53,...,0.56,1.1,1,Aditya Birla Sun Life Mutual Fund,3,Hybrid,Arbitrage Mutual Funds,5.6,4.8,5.5
2,Aditya Birla SL Asset Allocator FoF-Dir Growth...,Aditya Birla SL Asset Allocator FoF-Dir Growth,1000,1000,0.53,157.0,10,Vinod Narayan Bhat,3.44,2.67,...,0.67,1.42,5,Aditya Birla Sun Life Mutual Fund,3,Other,FoFs Domestic,2.0,18.9,9.7
3,Aditya Birla SL Bal Bhavishya Yojna – Dir Grow...,Aditya Birla SL Bal Bhavishya Yojna – Dir Growth,500,1000,0.76,637.0,4,Atul Penkar,2.18,-6.37,...,0.85,0.9,6,Aditya Birla Sun Life Mutual Fund,2,Solution Oriented,Childrens Funds,-0.7,17.1,0.0
4,Aditya Birla SL Balanced Advantage Fund 4.5,Aditya Birla SL Balanced Advantage Fund,100,100,0.61,6386.0,10,Mohit Sharma,3.69,1.99,...,0.68,1.39,6,Aditya Birla Sun Life Mutual Fund,4,Hybrid,Dynamic Asset Allocation or Balanced Advantage,4.5,18.6,9.7
5,Aditya Birla SL Banking&Financial Services-Dir...,Aditya Birla SL Banking&Financial Services-Dir...,1000,1000,1.17,2384.0,9,Dhaval Gala,2.07,1.24,...,0.96,0.97,6,Aditya Birla Sun Life Mutual Fund,2,Equity,Sectoral / Thematic Mutual Funds,5.3,24.6,9.2
6,Aditya Birla SL Banking&PSU Debt Fund 4.5,Aditya Birla SL Banking&PSU Debt Fund,1000,1000,0.37,7994.0,10,Kaustubh Gupta,1.92,4.46,...,1.78,1.09,3,Aditya Birla Sun Life Mutual Fund,4,Debt,Banking and PSU Mutual Funds,4.5,6.8,7.3
7,Aditya Birla SL CEF – Global Agri Plan-Direct ...,Aditya Birla SL CEF – Global Agri Plan-Direct ...,1000,1000,1.29,15.0,10,Vinod Narayan Bhat,1.42,-,...,-,1.06,6,Aditya Birla Sun Life Mutual Fund,0,Equity,Sectoral / Thematic Mutual Funds,-10.3,29.4,9.3
8,Aditya Birla SL Corporate Bond Fund 4.9,Aditya Birla SL Corporate Bond Fund,100,100,0.31,12120.0,10,Kaustubh Gupta,2.28,2.38,...,0.78,1.35,2,Aditya Birla Sun Life Mutual Fund,4,Debt,Corporate Bond Mutual Funds,4.9,7.1,7.4
9,Aditya Birla SL Credit Risk Fund 8.7,Aditya Birla SL Credit Risk Fund,100,100,0.69,1032.0,8,Sunaina da Cunha,1.82,3.01,...,-0.95,1.47,4,Aditya Birla Sun Life Mutual Fund,4,Debt,Credit Risk Funds,8.7,9.0,7.2

Changes After SQL Load fails

In [85]:
data['alpha']=data['alpha'].apply(lambda x:0 if x=='-' else x)
data['beta']=data['beta'].apply(lambda x:0 if x=='-' else x)
data['sortino']=data['sortino'].apply(lambda x:0 if x=='-' else x)
data['sd']=data['sd'].apply(lambda x:0 if x=='-' else x)
data['sharpe']=data['sharpe'].apply(lambda x:0 if x=='-' else x)

MySQL Integration SetUp

In [86]:
!pip install --upgrade mysql-connector-python
from mysql.connector import Error
import mysql.connector

Requirement already satisfied: mysql-connector-python in c:\users\arjun\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (8.3.0)

In [87]:
try:
    connection = mysql.connector.connect(host='localhost',
                                         port ='3306',
                                         user='Arjun',
                                         password='sql@2023')
    if connection.is_connected():
        print('Connected to MySQL database')
except Error as e:
    print(f"Error connecting to MySQL database: {e}")

Connected to MySQL database

In [88]:
cursor = connection.cursor()

Data Loading to SQL Database

In [89]:
try:
    cursor.execute("USE mutual_funds_db")

    # Create table
    cursor.execute("""
        CREATE TABLE Mutual_Funds (
            ID VARCHAR(255),
            scheme_name VARCHAR(255),
            min_sip DECIMAL(10, 2),
            min_lumpsum DECIMAL(10, 2),
            expense_ratio DECIMAL(5, 2),
            fund_size_cr DECIMAL(15, 2),
            fund_age_yr INT,
            fund_manager VARCHAR(255),
            sortino DECIMAL(10, 2),
            alpha DECIMAL(10, 2),
            sd DECIMAL(10, 2),
            beta DECIMAL(10, 2),
            sharpe DECIMAL(10, 2),
            risk_level VARCHAR(255),
            amc_name VARCHAR(255),
            rating VARCHAR(255),
            category VARCHAR(255),
            sub_category VARCHAR(255),
            returns_1yr DECIMAL(10, 2),
            returns_3yr DECIMAL(10, 2),
            returns_5yr VARCHAR(20)
        )
    """)

    # Write DataFrame to MySQL table row by row
    for index, row in data.iterrows():
        cursor.execute("""
            INSERT INTO Mutual_Funds 
            (ID, scheme_name, min_sip, min_lumpsum, expense_ratio, fund_size_cr, fund_age_yr, fund_manager,
            sortino, alpha, sd, beta, sharpe, risk_level, amc_name, rating, category, sub_category,
            returns_1yr, returns_3yr, returns_5yr)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """, tuple(row))

    # Commit changes
    connection.commit()
    print("Data loaded")

except Error as e:
    print(f"Error saving DataFrame to MySQL database: {e}")

Data loaded